### ISSUE TITLE
PySparkProcessor Uses Local Role Instead of Passed Role For Initial S3 File Movement

### ISSUE THREAD

**Issue by jimmycfa** [aws/sagemaker-python-sdk#1988] opened 2020-11-10 19:52 UTC
**Describe the bug**
PySparkProcessor uses the role used to call it when using the sagemaker SDK when it attempts to load local `submit_files` to S3 instead of using the `role` passed into it. The normal ScriptProcessor seems to use the passed in role. I got an access denied the first time I used PySparkProcessor when my calling role and passed in role were different. 

**To reproduce**
Create a PySparkProcessor and run it with a different role than the role passed into the instantiation. If the calling role doesn't have S3 permissions on *sagemaker* you will get an access denied even if the passed-in role does have *sagemaker* S3 permissions. I added `"Resource": "arn:aws:s3:::*sagemaker*"` to my calling role to get passed this.

**Expected behavior**
PySparkProcessor would use the passed in role to upload the local files to S3.

**Screenshots or logs**
Normal access denied error.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.16.2
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: PySparkProcessor
- **Framework version**: Unknown
- **Python version**: 3.7
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: Yes but just using sagemakerk==2.16.2

**Additional context**
None

**Comment by icywang86rui** [comment] 2020-11-18 19:44
@jimmycfa The SDK doesn't use the role passed in the Processor locally by design. The role parameter is passed to SageMaker service to start training jobs, processing jobs etc. Locally SDK caller could have different way to setup their credential, whatever local credential is used may not have permission to assumed the role specified in the parameter. 

We do have a get_execution_role here you can use to get the role name you are running the sdk code with - https://github.com/aws/sagemaker-python-sdk/blob/f43ff061979b713b15424a08e077f45c0b965167/src/sagemaker/session.py#L3627
Then you can pass that to the Processor constructor if desired. This is pattern in a lot of our example notebooks. Hope this answers your question. Resolving the issue. Feel free to reopen if you have any follow up questions.

**Closed by icywang86rui** 2020-11-18 19:44 UTC
