### ISSUE TITLE
Calling `pipeline.describe()` before `pipeline.start()` is breaking the cache config for the TrainingStep.

### ISSUE THREAD

**Issue by cristopherfreitas** [aws/sagemaker-python-sdk#3555] opened 2022-12-20 20:52 UTC
**Describe the bug**
Given that I have the pipeline properly set, and I'm using cache for the TrainingStep, if I run `pipeline.describe()`, then `pipeline.upsert()` and `pipeline.start()`, I'm getting an error: 

```
ClientError: Failed to invoke sagemaker:CreateTrainingJob. Error Details: ProfilerConfig is not allowed to have fields when disabled.
```

**To reproduce**
This is what the training step looks like:
```python
pipeline_session = PipelineSession()

# Enable caching for the Training step with 30 days expiration date
# The expiration date follows ISO-8601 https://en.wikipedia.org/wiki/ISO_8601#Durations
cache_config = CacheConfig(enable_caching=True, expire_after="P1M")

# Training step for generating model artifacts
model_path = f"s3://{sagemaker_session.default_bucket()}/{base_job_prefix}/train"

model_train = PyTorch(
    entry_point='build.py',
    region=region,
    framework_version="1.12",
    py_version="py38",
    instance_type="ml.m5.xlarge",
    instance_count=1,
    output_path=model_path,
    base_job_name=f"{base_job_prefix}/train",
    sagemaker_session=pipeline_session,
    role=role,
    source_dir=BASE_DIR,
    disable_profiler=True
)

step_train = TrainingStep(
    name=f"{base_job_prefix}Train",
    estimator=model_train,
    cache_config=cache_config
)
```

This is the code to create the pipeline:
```python
print("###### Creating/updating a SageMaker Pipeline with the following definition:")
parsed = json.loads(pipeline.definition())
print(json.dumps(parsed, indent=2, sort_keys=True))

all_tags = get_pipeline_custom_tags(args.module_name, args.kwargs, tags)

upsert_response = pipeline.upsert(
    role_arn=args.role_arn, description=args.description
)

print("\n###### Created/Updated SageMaker Pipeline: Response received:")
print(upsert_response)

execution = pipeline.start()
print(f"\n###### Execution started with PipelineExecutionArn: {execution.arn}")

print("Waiting for the execution to finish...")
```

**Expected behavior**
I would expect the pipeline to run in the same behavior as if I haven't run `pipeline.describe()`. 

**Screenshots or logs**
<img width="386" alt="image" src="https://user-images.githubusercontent.com/89938554/208764029-db8c23ea-c2cc-4d9b-82e3-f9a3542d7f8b.png">

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.125.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: PyTorch
- **Framework version**: 1.12
- **Python version**: 3.8
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**
Looking into the differences between a successful and a failed execution, I found this extra field when failing: `ProfilerConfig.S3OutputPath`. 

It seems that calling `pipeline.describe()` adds this field in the pipeline configuration even with `disable_profiler=True` in the `PyTorch` estimator.

**Comment by brockwade633** [comment] 2022-12-31 22:10
Hi @cristopherfreitas, thanks for the info. A couple notes: 
- It seems from your description that `pipeline.describe()` is causing you problems, not `pipeline.definition()`. If that's true, would you update the issue title?
- So far I'm unable to reproduce the `CreateTrainingJob` error using your code above (substituting a different entrypoint) in a pipeline with just the single training step. I've tried varying configurations of the following snippet, with no problems.
```
print(pipeline.describe())

parsed=json.loads(pipeline.definition())
print(json.dumps(parsed, indent=2, sort_keys=True))

upsert_response = pipeline.upsert(role_arn=ROLE)
print(upsert_response)

execution = pipeline.start()
```
Can you provide more of your code that is producing the error? Such as the code to actually define the pipeline (any other steps included?), the region, "args" variable, etc. Thanks.

**Comment by stephenhunter-mdfwork** [comment] 2023-01-03 07:29
My pipeline runs started breaking with the same error a couple of weeks ago. I managed to get them working again by passing a `profiler_config` to the `Estimator()` creation step, setting `s3_output_path=None` and `disable_profiler=True`. Previously I did not supply a `profiler_config` argument to the `Estimator()`, but did have `debugger_hook_config=False` and `disable_profiler=True`. In my case it was a TensorFlow Estimator. 

```
profiler_config = ProfilerConfig(
    s3_output_path=None,
    disable_profiler=True
)
```

**Comment by qidewenwhen** [comment] 2023-01-06 18:35
Hi @cristopherfreitas, the issue you're facing: `ClientError: Failed to invoke sagemaker:CreateTrainingJob. Error Details: ProfilerConfig is not allowed to have fields when disabled.` seems relate to a breaking change brought in in PySDK v2.124.0. (See other reports [here](https://github.com/aws/sagemaker-python-sdk/commit/92358fe20b5f8a390edc81b0d17a013612f7245a#commitcomment-93687270)). That's why @brockwade633  is not able to reproduce the issue with your code sample.

The breaking change's owner has been actively fixing the issue, so could you upgrade you PySDK and check if the issue has been fixed?
If no, could you try stephenhunter-mdfwork@'s suggestion to bypass the issue?

Sorry for the inconvenience and thanks @stephenhunter-mdfwork for sharing this great solution!

**Comment by brockwade633** [comment] 2023-01-19 18:49
Hi @cristopherfreitas, did the latest SDK version resolve the ClientError you were experiencing?

**Comment by brockwade633** [comment] 2023-01-19 19:33
No problem @cristopherfreitas, we'll keep this open and look forward to getting more details from you when you're able.

**Comment by brockwade633** [comment] 2023-02-17 02:49
Hi @cristopherfreitas, is there any update on this - are you still experiencing the ClientError in the latest PySDK version?

**Comment by brockwade633** [comment] 2023-03-01 21:32
No problem, closing as issue has been resolved in later PySDK version.

**Closed by brockwade633** 2023-03-01 21:32 UTC
Labels: bug, component: pipelines
