### ISSUE TITLE
Local mode errors for PySparkProcessor for instance_type="local"

### ISSUE THREAD

**Issue by j-adamczyk** [aws/sagemaker-python-sdk#4024] opened 2023-07-26 11:22 UTC
**Describe the bug**
When I run PySparkProcessor with `instance_type="local"`, it results in error:
```
INFO:sagemaker.local.image:docker command: docker-compose -f /tmp/tmploom4z89/docker-compose.yaml up --build --abort-on-container-exit
Creating q23qsy3y31-algo-1-2ptps ... 
Creating q23qsy3y31-algo-1-2ptps ... done
Attaching to q23qsy3y31-algo-1-2ptps
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark.cli  INFO     Parsing arguments. argv: ['/usr/local/bin/smspark-submit', '--jars', '/opt/ml/processing/input/jars', '/opt/ml/processing/input/code/spark_script.py']
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark.cli  INFO     Raw spark options before processing: {'jars': '/opt/ml/processing/input/jars', 'class_': None, 'py_files': None, 'files': None, 'verbose': False}
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark.cli  INFO     App and app arguments: ['/opt/ml/processing/input/code/spark_script.py']
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark.cli  INFO     Rendered spark options: {'jars': '/opt/ml/processing/input/jars/elasticsearch-spark-30_2.12-8.8.2.jar', 'class_': None, 'py_files': None, 'files': None, 'verbose': False}
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark.cli  INFO     Initializing processing job.
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     {'current_host': 'algo-1-2ptps', 'hosts': ['algo-1-2ptps']}
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     {'ProcessingJobArn': 'prepare-targets-2023-07-26-11-18-06-218', 'ProcessingJobName': 'prepare-targets-2023-07-26-11-18-06-218', 'AppSpecification': {'ImageUri': '906073651304.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-spark-processing:3.3-cpu-py39-v1', 'ContainerEntrypoint': ['smspark-submit', '--jars', '/opt/ml/processing/input/jars', '/opt/ml/processing/input/code/spark_script.py'], 'ContainerArguments': None}, 'Environment': {}, 'ProcessingInputs': [{'InputName': 'jars', 'AppManaged': False, 'S3Input': {'S3Uri': 's3://sagemaker-eu-central-1-590463175157/prepare-targets-2023-07-26-11-18-06-218/input/jars', 'LocalPath': '/opt/ml/processing/input/jars', 'S3DataType': 'S3Prefix', 'S3InputMode': 'File', 'S3DataDistributionType': 'FullyReplicated', 'S3CompressionType': 'None'}, 'DataUri': 's3://sagemaker-eu-central-1-590463175157/prepare-targets-2023-07-26-11-18-06-218/input/jars'}, {'InputName': 'code', 'AppManaged': False, 'S3Input': {'S3Uri': 's3://sagemaker-eu-central-1-590463175157/prepare-targets-2023-07-26-11-18-06-218/input/code/spark_script.py', 'LocalPath': '/opt/ml/processing/input/code', 'S3DataType': 'S3Prefix', 'S3InputMode': 'File', 'S3DataDistributionType': 'FullyReplicated', 'S3CompressionType': 'None'}, 'DataUri': 's3://sagemaker-eu-central-1-590463175157/prepare-targets-2023-07-26-11-18-06-218/input/code/spark_script.py'}], 'ProcessingOutputConfig': {}, 'ProcessingResources': {'ClusterConfig': {'InstanceCount': 1, 'InstanceType': 'local', 'VolumeSizeInGB': 30, 'VolumeKmsKeyId': None}}, 'RoleArn': '<no_role>', 'StoppingCondition': {'MaxRuntimeInSeconds': 86400}}
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark.cli  INFO     running spark submit command: spark-submit --master yarn --deploy-mode client --jars /opt/ml/processing/input/jars/elasticsearch-spark-30_2.12-8.8.2.jar /opt/ml/processing/input/code/spark_script.py
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     waiting for hosts
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     starting status server
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     Status server listening on algo-1-2ptps:5555
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     bootstrapping cluster
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     transitioning from status INITIALIZING to BOOTSTRAPPING
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     copying aws jars
q23qsy3y31-algo-1-2ptps | 07-26 11:18 waitress     INFO     Serving on http://172.18.0.2:5555
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     Found hadoop jar hadoop-aws.jar
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     Optional jar jets3t-0.9.0.jar in /usr/lib/hadoop/lib does not exist
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     copying cluster config
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     copying /opt/hadoop-config/hdfs-site.xml to /usr/lib/hadoop/etc/hadoop/hdfs-site.xml
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     copying /opt/hadoop-config/core-site.xml to /usr/lib/hadoop/etc/hadoop/core-site.xml
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     copying /opt/hadoop-config/yarn-site.xml to /usr/lib/hadoop/etc/hadoop/yarn-site.xml
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     copying /opt/hadoop-config/spark-defaults.conf to /usr/lib/spark/conf/spark-defaults.conf
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     copying /opt/hadoop-config/spark-env.sh to /usr/lib/spark/conf/spark-env.sh
q23qsy3y31-algo-1-2ptps | 07-26 11:18 smspark-submit INFO     exiting with code 1: Algorithm Error: (caused by KeyError): error running Spark job: 'local'
q23qsy3y31-algo-1-2ptps exited with code 1
1
Aborting on container exit...
```

**To reproduce**

Run example for Local Mode with PySparkProcessor from the docs:
```
import boto3
from sagemaker.local import LocalSession
from sagemaker.spark.processing import PySparkProcessor

boto_session = boto3.session.Session(
    profile_name="my_profile",
    region_name="eu-central-1"
)

sagemaker_session = LocalSession(boto_session)
sagemaker_session.config = {"local": {"local_code": True}}

pyspark_processor = PySparkProcessor(
    sagemaker_session=sagemaker_session,
    base_job_name="prepare-targets",
    framework_version="3.3",
    py_version="py39",
    container_version="1",
    role="arn:aws:iam::590463175157:role/service-role/sagemaker-role",
    instance_count=1,
    instance_type="local",
)

pyspark_processor.run(
    submit_app="spark_script.py",
)
```

However, when passing any EC2 instance type, e.g. `instance_type="ml.m4.xlarge"`, it works without a problem.

**Expected behavior**
Work normally. Instance type is ignored in local mode anyway

**System information**
- **SageMaker Python SDK version**: 2.173.0
- **Python version**: 3.10.6
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Comment by martinRenou** [comment] 2023-10-03 14:21
Closing as duplicate of https://github.com/aws/sagemaker-spark-container/issues/65

**Closed by martinRenou** 2023-10-03 14:21 UTC
Labels: bug
