### ISSUE TITLE
TensorFlow - Deploy from an attached a training job does not create an endpoint successfully

### ISSUE THREAD

**Issue by jonsnowseven** [aws/sagemaker-python-sdk#663] opened 2019-02-26 14:23 UTC
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: **TensorFlow / Neural Network**
- **Framework Version**: 1.12
- **Python Version**:
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.16.3
- **Are you using a custom image**: No

### Description

Deploying from an attached training job does not create an endpoint successfully.

Description of the model in the working endpoint:

```json
{
    "ModelName": "*",
    "PrimaryContainer": {
        "Image": "520713654638.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-tensorflow-serving:1.12-cpu",
        "ModelDataUrl": "s3://*/model.tar.gz",
        "Environment": {
            "SAGEMAKER_TFS_NGINX_LOGLEVEL": "debug"
        }
    },
    "ExecutionRoleArn": "*",
    "VpcConfig": {
        "SecurityGroupIds": [
            "sg-*"
        ],
        "Subnets": [
            "subnet-*",
            "subnet-*"
        ]
    },
    "CreationTime": 1551175221.987,
    "ModelArn": "*",
    "EnableNetworkIsolation": false
}
```

Description of the model in the non working endpoint:

```json
{
    "ModelName": "*",
    "PrimaryContainer": {
        "Image": "520713654638.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-tensorflow-scriptmode:1.12-cpu-py3",
        "ModelDataUrl": "s3://*/model.tar.gz",
        "Environment": {
            "SAGEMAKER_CONTAINER_LOG_LEVEL": "10",
            "SAGEMAKER_ENABLE_CLOUDWATCH_METRICS": "false",
            "SAGEMAKER_PROGRAM": "main.py",
            "SAGEMAKER_REGION": "*",
            "SAGEMAKER_SUBMIT_DIRECTORY": "s3://*/sourcedir.tar.gz"
        }
    },
    "ExecutionRoleArn": "*",
    "VpcConfig": {
        "SecurityGroupIds": [
            "sg-*"
        ],
        "Subnets": [
            "subnet-*",
            "subnet-*"
        ]
    },
    "CreationTime": 1551186150.979,
    "ModelArn": "*",
    "EnableNetworkIsolation": false
}
```

### Minimal repro / logs

```
Traceback (most recent call last):
File "/usr/local/bin/serve", line 11, in <module>
load_entry_point('sagemaker-containers==2.4.2', 'console_scripts', 'serve')()
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/cli/serve.py", line 17, in main
server.start(env.ServingEnv().framework_module)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_server.py", line 73, in start
nginx = subprocess.Popen(['nginx', '-c', nginx_config_file])
File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
restore_signals, start_new_session)
File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nginx': 'nginx'
```

- **Exact steps to reproduce**:
* Create e training job that runs successfully using TensorFlow Script Mode (either way is fine).
* Using SDK, attach that training job and use the resulting estimator to deploy an endpoint.
* The endpoint does not pass the ping health check.

The issue is pretty straight forward to reproduce but please let me know if you need me to supply some code.

Thank you in advance.

**Comment by nadiaya** [comment] 2019-03-06 00:15
It is a bug since it tries to use '520713654638.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-tensorflow-scriptmode:1.12-cpu-py3' image that doesn't support hosting and TFS container should be used instead.

Since it is caused by https://github.com/aws/sagemaker-python-sdk/issues/671 closing this one as a duplicate.

**Closed by nadiaya** 2019-03-06 00:15 UTC

**Comment by jonsnowseven** [comment] 2019-03-06 09:21
Hello @nadiaya.

Thank you for your answer.

I'll follow #671 instead.

Best regards,

João Neves

**Comment by filthysocks** [comment] 2019-06-05 11:49
the image name is wrong. Use 520713654638.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-tensorflow-serving:1.12.0-cpu and it should work
