### ISSUE TITLE
RealTimePredictor.accept values not correctly checked

### ISSUE THREAD

**Issue by vanoudh** [aws/sagemaker-python-sdk#993] opened 2019-08-22 21:40 UTC
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: RealTimePredictor
- **Framework Version**: 
- **Python Version**: notebook kernel conda_tensorflow_p36
- **CPU or GPU**: CPU
- **Python SDK Version**: sagemaker 1.35.1
- **Are you using a custom image**:

### Describe the problem

The accept parameter is not correctly checked when set on a RealTimePredictor. 

If we set accept to a value not supported, it will default to application/json instead of throwing an error.

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

from sagemaker.predictor import RealTimePredictor

predictor = RealTimePredictor('linear-learner-2019-08-22-15-54-26-888')

predictor.content_type = 'text/csv'
predictor.serializer = csv_serializer
predictor.accept = 'text/csv'     # this is not a valid value
predictor.deserializer = csv_deserializer
predictor.predict(x_test)

output:

[['{"predictions": [{"score": 0.39518389105796814',
  ' "predicted_label": 0.0}',
  ' {"score": 0.6770541667938232',
  ' "predicted_label": 1.0}',
  ' {"score": 0.013649559579789639',
  ' "predicted_label": 0.0}',

**Comment by ChoiByungWook** [comment] 2019-08-30 19:52
Hello @vanoudh,

Apologies for the late response.

Thanks for bringing this to our attention.

Just for clarification, can you please elaborate on what the issue is, as how I understand it is that 'text/csv' shouldn't be a valid accept value for your algorithm, however it doesn't error out and instead returns the result as JSON blobs. Is that correct?

For reference:

https://docs.aws.amazon.com/sagemaker/latest/dg/linear-learner.html#ll-input_output
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/predictor.py#L74

**Comment by vanoudh** [comment] 2019-08-30 23:48
Hi Dan,

Yes. It may not be a bug but it is very confusing. It would be much better to return an error when the server cannot return the client accept type.

It is also confusing because the documentation says text/csv is supported. From my tests it is only supported as input, not as output.

Thank you

**Comment by ChoiByungWook** [comment] 2019-08-31 00:05
I agree.

The expected experience should be that if that a specific accept type isn't supported, then an error should be returned.

In addition, the documentation should be more clear.

Let me route this to proper team.

Thanks!

**Comment by yastasho** [comment] 2019-09-03 19:26
Thanks for the feedback, we're going to revisit the behavior of the algorithms when an unsupported accept media type is provided.
I would also like to inform that linear learner has been updated with support of 'text/csv' accept type. It is possible to produce predictions in CSV format now.

**Comment by vanoudh** [comment] 2019-09-03 20:18
Excellent thank you!

**Comment by martinRenou** [comment] 2023-09-28 10:50
Closing as fixed. Thank you!

**Closed by martinRenou** 2023-09-28 10:50 UTC
Labels: type: feature request, type: documentation
