### ISSUE TITLE
AttributeError: 'CustomFramework' object has no attribute 'framework_version'

### ISSUE THREAD

**Issue by jagadeesr** [aws/sagemaker-python-sdk#3079] opened 2022-04-25 22:07 UTC
**Describe the bug**
Calling this estimator.fit(inputs) fails with error

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.

**Expected behavior**

Follow this tutorial:
https://github.com/aws-samples/amazon-sagemaker-tensorflow-object-detection-api/blob/main/2_train_model/train_model.ipynb

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.
![image](https://user-images.githubusercontent.com/1259732/165182721-d2dcc6ff-418c-4d01-bfe3-bc4e895f1550.png)

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.87.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: CustomFramework
- **Framework version**: 
- **Python version**: 3.7, 3.8
- **CPU or GPU**: both
- **Custom Docker image (Y/N)**: Y

**Additional context**
Trying to build Tensorflow object detection API framework with custom container
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_training_and_evaluation.md

class CustomFramework(Framework):
    def __init__(
        self,
        entry_point,
        framework_version="2.2.0",  # now required
        py_version="py37",
        source_dir=None,
        hyperparameters=None,
        distributions=None,
        **kwargs
    ):
        super(CustomFramework, self).__init__(entry_point, source_dir, hyperparameters, **kwargs)
    
    def _configure_distribution(self, distributions):
        return
    
    def create_model(
        self,
        framework_version="2.2.0",  # now required
        py_version="py37",
        model_server_workers=None,
        role=None,
        vpc_config_override=None,
        entry_point=None,
        source_dir=None,
        dependencies=None,
        image_uri=None,
        **kwargs
    ):
        return None

**Comment by BelkissDS** [comment] 2022-05-04 14:25
I had the same issue.
When defining the class Custom framework, I added the two attributes **framework_version** and py_version initialized to None and it worked fine 

`from sagemaker.estimator import Framework

class CustomFramework(Framework):
    def __init__(
        self,
        entry_point,
        framework_version=None,
        py_version=None,
        source_dir=None,
        hyperparameters=None,
        image_uri=None,
        distribution=None,
        **kwargs
    ):
        super(CustomFramework, self).__init__(
            entry_point, source_dir, hyperparameters, image_uri=image_uri, **kwargs
        )
        self.framework_version = framework_version
        self.py_version = None
        
    def _configure_distribution(self, distributions):
        return None

    def create_model(
        self,
        model_server_workers=None,
        role=None,
        vpc_config_override=None,
        entry_point=None,
        source_dir=None,
        dependencies=None,
        image_uri=None,
        **kwargs
    ):
        return None`

**Comment by navinsoni** [comment] 2022-12-13 19:34
@jagadeesr and @BelkissDS This is expected behavior. We don't have to provide `framework_version` and `py_version` if image_uri is provided.

Hope this answers your que.

**Comment by zhaoqizqwang** [comment] 2024-05-06 16:44
Close this ticket since this is the expected behavior

**Closed by zhaoqizqwang** 2024-05-06 16:44 UTC
Labels: bug, Custom Framework
