### ISSUE TITLE
 modelpackage method does'nt override the  prepare_container_def method

### ISSUE THREAD

**Issue by RominaUQ** [aws/sagemaker-python-sdk#2739] opened 2021-10-29 10:11 UTC
Unable to  to deploy one version of the model from Model registry into an **existing endpoint**. Direct deployment works fine but updating endpoint is not possible. As ModelPackage class inherit from Model class we tried to retrofit a work around as below by getting the container_def- this work around was due to the other issue reported here: :[https://github.com/aws/sagemaker-python-sdk/issues/1920] due to update=TRUE option being removed from the endpoint update.

```
model = ModelPackage(role="AmazonSageMakerRole", model_package_arn='arn:aws:sagemaker:ap-southeast-*********:model-package/new-digit-classification-group/3',
                    sagemaker_session=sm_session)

timestamp = time.strftime("-%Y-%m-%d-%H-%M", time.gmtime())

container_def = model.prepare_container_def(instance_type="ml.c5.xlarge")

print(container_def)

new_model_name = f"MNIST-model-{timestamp}"

sm_session.create_model(new_model_name, role="AmazonSageMakerRole", container_defs=container_def)

endpoint_name = "MNIST-endpoint--2021-10-12-22-47"

predictor = Predictor(endpoint_name)

predictor.update_endpoint(model_name=new_model_name, initial_instance_count=1, instance_type="ml.c5.xlarge")
 
```
However the code fails at sm_session.create_model as container_def returned by model.prepare_container_def return a empty dictionary as per below.
`{'Image': None, 'Environment': {}}`
 
Rephrasing the issue: deploying a specific model version from a Model Registry group into an existing endpoint by update endpoint is not possible using sagemaker Python SDK.

**Comment by abhinakv-aws** [comment] 2024-08-06 07:27
![Uploading Screenshot 2024-08-06 at 12.54.15 PM.png…]()

**Comment by abhinakv-aws** [comment] 2024-08-06 07:28
Tried reproducing the error but looks like the code mentioned above does work. The update_endpoint() method is also working and the same is being successful. Also, the print(container_def) is not empty:
```
 {'Image': 'mi', 'Environment': {'SAGEMAKER_PROGRAM': 'inference.py', 'SAGEMAKER_SUBMIT_DIRECTORY': 's3://codebucket/someprefix/sourcedir.tar.gz', 'SAGEMAKER_CONTAINER_LOG_LEVEL': '20', 'SAGEMAKER_REGION': 'us-west-2'}, 'ModelDataUrl': {'_step': None, 'step_name': 'Steps.MyStep', 'path': None, '_shape_names': []}}
```

**Comment by abhinakv-aws** [comment] 2024-08-06 07:29
<img width="1493" alt="Screenshot 2024-08-06 at 12 54 15 PM" src="https://github.com/user-attachments/assets/c46424a3-ce4a-4b7a-a93d-215a40fa3202">

**Comment by abhinakv-aws** [comment] 2024-08-06 08:35
Resolving as the issue has been fixed in the sdk package now

**Comment by sage-maker** [comment] 2024-08-06 10:00
Marking as closed per @abhinakv-aws

**Closed by sage-maker** 2024-08-06 10:00 UTC
Labels: bug, type: feature request
