### ISSUE TITLE
UnicodeDecodeError with README.rst

### ISSUE THREAD

**Issue by pabloheimplatz** [aws/sagemaker-python-sdk#169] opened 2018-05-07 09:31 UTC
### System Information
- **Python Version**: 3.6.4
- **CPU or GPU**: Macbook Air 2017

### Describe the problem
There is a problem with the `README.rst`. Python gave me an `UnicodeDecodeError`. I tried to install with pip and directly from this repo. Both throw the error I posted below.

Solution for me: I cleared the `README.rst` so that there are no ASCI oder UTF-8 symbols in it. Works fine on my local Macbook.

### Minimal repo / logs
```
$ pip install SageMaker
Collecting SageMaker
  Using cached https://files.pythonhosted.org/packages/81/13/709f55a8a74e8a3c7ead5a68453b82694c0d6a37fa4fdab0ac868fd5b4d8/sagemaker-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m9/lqnkhvb16w18p7wg6rx06c8w0000gq/T/pip-install-yhyu0eez/SageMaker/setup.py", line 19, in <module>
        long_description=read('README.rst'),
      File "/private/var/folders/m9/lqnkhvb16w18p7wg6rx06c8w0000gq/T/pip-install-yhyu0eez/SageMaker/setup.py", line 10, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5556: ordinal not in range(128)

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/m9/lqnkhvb16w18p7wg6rx06c8w0000gq/T/pip-install-yhyu0eez/SageMaker/
```

**Comment by laurenyu** [comment] 2018-05-07 17:00
Thanks for reporting this! Since you mentioned that you already went through the README and removed the offending characters, would you be interested in submitting a pull request with the fix?

**Comment by pabloheimplatz** [comment] 2018-05-08 06:27
Unfortunately I removed the whole README because I didn't found the wrong character. Thats why I can't submitting a pull request. I'm sorry. Maybe I can try it later again. If I found it I send you a pull request.

**Comment by laurenyu** [comment] 2018-05-08 16:00
oh, I see. I've tried to reproduce the error, but it's been working fine for me with Python versions 3.5, 3.6.4, and 3.6.5.

The character at position 5556 looks to be the period in [this line](https://github.com/aws/sagemaker-python-sdk/blame/master/README.rst#L151). In my editor, the first space after that period was displayed as a red underline instead of just a space. If you have a chance, would you mind trying deleting that and re-building?

**Comment by yangaws** [comment] 2018-07-30 23:44
The PR is merged. And we haven't got any bug reports till now.

So I will close this. Feel free to reopen if anybody gets the bug again.

**Closed by yangaws** 2018-07-30 23:44 UTC
Labels: bug
