### ISSUE TITLE
Support pyspark 3.0.0

### ISSUE THREAD

**Issue by filipe-plutoflume** [aws/sagemaker-python-sdk#1825] opened 2020-08-12 17:49 UTC
**Describe the bug**
As it is sagemaker does not support the latest version of pyspark:

![image](https://user-images.githubusercontent.com/47322240/90049100-42c70600-dccc-11ea-8a28-664c9dc3fda8.png)

**To reproduce**
`pip install pyspark==3.0.0`

```
import pyspark
import sagemaker_pyspark
from pyspark.sql import SparkSession
from pyspark.sql import functions as f
 
classpath = ":".join(sagemaker_pyspark.classpath_jars())
spark = (SparkSession.builder.config("spark.driver.extraClassPath", classpath)
    .config("spark.local.dir", "/home/ec2-user/SageMaker/tmp/spark-temp") # use Sagemaker disk as tmp location
    .config("spark.sql.parquet.compression.codec", "none")
    .config("spark.driver.memory", "15G")
    .config("spark.executor.memory", "10G")
    .config("spark.driver.maxResultSize","15G")
    .config("spark.executorEnv.DATABASE_URL", "")
    .config("spark.executorEnv.LOG_ENCRYPT_SECRET_KEY", "")
    .config("spark.executorEnv.MY_URL", "")
    .config("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
    .config("fs.s3a.connection.maximum", "100")
    .getOrCreate())
spark.read.parquet('s3a://path/to/parquet')
```

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: PySpark
- **Framework version**:
- **Python version**: 3.6.10
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**

**Comment by metrizable** [comment] 2020-08-13 14:52
@filipe-plutoflume Thanks for using Amazon SageMaker.

This request is for a feature in the [sagemaker-spark](https://github.com/aws/sagemaker-spark) repo and should be tracked there. In that repo, it is a duplicate of [#120](https://github.com/aws/sagemaker-spark/issues/120). I'm closing this issue in favor of [#120](https://github.com/aws/sagemaker-spark/issues/120).

**Closed by metrizable** 2020-08-13 14:52 UTC
Labels: type: unrelated to Python SDK
