### ISSUE TITLE
ValueError(f"Bad value for instance type: '{instance_type}'")

### ISSUE THREAD

**Issue by mlsquareup** [aws/sagemaker-python-sdk#3993] opened 2023-07-12 15:44 UTC
**Describe the bug**
Good Morning, I get an error when trying to create a pipeline execution, after updating sagemaker, as follows:

```
...Traceback Messages...
  File "blah/blah", line xxxx, in get_estimator
    estimator = Estimator(
  File "/var/task/sagemaker/estimator.py", line 2896, in __init__
    super(Estimator, self).__init__(
  File "/var/task/sagemaker/estimator.py", line 622, in __init__
    raise ValueError(f"Bad value for instance type: '{instance_type}'")
  File "/var/task/sagemaker/workflow/entities.py", line 86, in __str__
    raise TypeError(
TypeError: Pipeline variables do not support __str__ operation. Please use `.to_string()` to convert it to string type in execution timeor use `.expr` to translate it to Json for display purpose in Python SDK.
+ [[ False = True ]]
```

Firstly the TypeError is incorrect, I don't want to to_string() the pipeline variable right off the bat, as I don't know what instance type I will need. I want to dynamically assign an instance_type after I've estimated the resources required to run a job. This resource estimation is part of our pipeline. 

**To reproduce**
Try to create an estimator with instance_type = a PipelineVariable with recent version of sagemaker==2.171.0

**Expected behavior**
Before recent [changes](https://github.com/aws/sagemaker-python-sdk/blame/baf96cd540dd9c46ee72e730f9904623184d2844/src/sagemaker/estimator.py#L617-L622) I was able to dynamically assign an instance type. Now I have to do some kind of workaround, such as using ConditionStep and JsonGet'ing the type. Or some other workaround, if you could please provide any suggestions.

Is this expected behavior? Is the point that each step should be assigned an instance_type at pipeline execution start or is there another reason? If not, assigning an instance_type is important as we want to accurately estimate the resources for a training job rather than overprovision or guess too early. We have files that might have high compression ratios that we cannot accurate gauge the size of early on.

**Comment by eugeneyarovoi** [comment] 2023-07-12 18:03
To summarize the problem a bit more compactly: it seems that as of this writing, the newer versions of the sagemaker Python package (e.g. 2.171.0), require `instance_type` as passed to `Estimator` to be `str` or `ParameterString`. But ours is a different kind of `PipelineVariable`, namely a `JsonGet`, where we get the value from a property file. This was valid in earlier versions.

Is there a reason it was changed now, or is it a bug?

**Comment by mlsquareup** [comment] 2023-07-19 21:48
Hi @evakravi, we noticed the recent change you made doesn't evaluate the ParameterString value, but uses the default_value. This might let an invalid instance_type pass if its default_instance_type is valid for the volume.

We're considering creating a PR to modify this logic. We want to use a PipelineVariable akin to a JsonGet (as we've done before), allowing us to assign an instance_type later in the pipeline execution instead of at the start. So basically we need to bypass the check altogether because we can't know the volume ahead of time. 

Could you please provide more context for your change, to help us understand if our approach is okay?

**Comment by qidewenwhen** [comment] 2023-08-05 00:20
A note for following oncalls and contributors: this seems to be a similar issue as https://github.com/aws/sagemaker-python-sdk/issues/3917

A fix https://github.com/aws/sagemaker-python-sdk/pull/3972 has been merged and released in v2.171.0 to fix the issue but it does not seem to cover this issue #3993 case.

**Comment by qidewenwhen** [comment] 2023-08-10 00:30
Putting a summary here for the regression resulted from https://github.com/aws/sagemaker-python-sdk/pull/3870:
- https://github.com/aws/sagemaker-python-sdk/issues/3917: 
  - the breaking point was in `volume_size_supported` 
  - we've pushed a fix to resolve it already: https://github.com/aws/sagemaker-python-sdk/pull/3972
- This https://github.com/aws/sagemaker-python-sdk/issues/3993: 
  - The breaking point is in `EstimatorBase.__init__` (see [changes](https://github.com/aws/sagemaker-python-sdk/blame/baf96cd540dd9c46ee72e730f9904623184d2844/src/sagemaker/estimator.py#L617-L622))
  - This breaking point is critical as it is disallowing any pipeline variables except `ParameterString`. This would significantly impact customer experience as Michael stated in the issue overview.

Tagging the change owner @evakravi for more context, can we fix this issue and make your change backward compatible?

**Comment by qidewenwhen** [comment] 2023-08-10 00:36
Also, out of curious why this breaking change was not caught by any pipeline variable related tests, given that it's thrown directly from the EstimatorBase.__init__.

Hi @mlsquareup, could you share your code sample especially the part defining the `Estimator` and training step etc. which relates to the exception? That can help us to reproduce the issue and improve our tests.

Also you've mentioned that:
> We're considering creating a PR to modify this logic. 

Have you opened a PR or have done that locally already?

Thanks!

**Comment by eugeneyarovoi** [comment] 2023-08-10 11:29
I work with @mlsquareup. We haven't created such a PR yet, as we were first looking to get feedback explaining why the change was made in the first place. We'd still rather someone with more familiarity with the codebase than us make the change (this is the first time we've looked at the source), if that's possible and something folks are interested in addressing.

**Comment by qidewenwhen** [comment] 2023-08-10 21:36
Thanks @eugeneyarovoi for confirming! 
I was asking this to avoid duplicate work. I'll reach out to the change owner offline to understand the change and work on a fix.

**Closed** 2023-08-15 21:08 UTC
Labels: bug, component: pipelines
