### ISSUE TITLE
ModelName property from CreateModelStep is not accessible

### ISSUE THREAD

**Issue by clennan** [aws/sagemaker-python-sdk#2432] opened 2021-06-08 12:53 UTC
**Describe the bug**
The `ModelName` property from a `CreateModelStep` cannot be referenced by subsequent `ProcessingStep`. We followed the step properties as described in step 7 of the developer guide example https://docs.aws.amazon.com/sagemaker/latest/dg/define-pipeline.html

**To reproduce**
```python
from sagemaker.tensorflow import TensorFlowModel
from sagemaker.workflow.steps import CreateModelStep

model = TensorFlowModel(
    entry_point="modules/inference.py",
    source_dir='./modules',
    model_data="s3://path/to/model.tar.gz",
    role=role,
    framework_version="2.4.1",
    sagemaker_session=sagemaker_session,
)

inputs = sagemaker.inputs.CreateModelInput(instance_type="ml.m5.xlarge")
create_model_step = CreateModelStep(name="ModelCreation", model=model, inputs=inputs)
```

```python
from sagemaker.workflow.steps import ProcessingStep
                                                     
deploy_step = ProcessingStep(
    name="DeployModel",
    processor=custom_script_processor,
    code="modules/deploy.py",
    job_arguments=[
        "--model-name",
        create_model_step.properties.ModelName,
        "--endpoint-instance-type",
        "ml.m5.xlarge",
        "--endpoint-name",
        "classification-endpoint",
    ],
)
```

```python
from sagemaker.workflow.pipeline import Pipeline

deploy_pipeline = Pipeline(
    name="ClassificationDeploymentPipeline",
    steps=[create_model_step, deploy_step],
)
```
In our `deploy.py` script the job argument `--model-name` is `None` and not the model name we would expect under the property `create_model_step.properties.ModelName`.

**Expected behavior**
We expect that the pipeline would dynamically resolve the model name in **deploy_step** where we reference the property `create_model_step.properties.ModelName` from **create_model_step**.

**System information**
A description of your system. Please provide: 
- **SageMaker Python SDK version**: 2.44.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: TensorFlow
- **Framework version**: 2.4.1
- **Python version**: 3.7
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: Y

**Comment by dgallitelli** [comment] 2021-06-22 12:39
I can confirm this happens regardless of the framework version and SDK version. It is a problem in the arguments passed to the `create_model()` request (ref: [L250](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/workflow/steps.py#L250)).

**Comment by navaj0** [comment] 2021-06-28 22:40
Hi clennan@, I'm trying to investigate the issue, but I'm not able to reproduce what you saw. 

I have a processing step
```
step_eval = ProcessingStep(
    name="AbaloneEval",
    processor=script_eval,
    code="abalone/evaluation.py",
    job_arguments=[
        "--model-name",
        step_create_model.properties.ModelName
    ]
)
```
and the script simply does a print
```
if __name__ == "__main__":
    print(sys.argv[1:])
```
I'm able to see the model name in the processing job log.

**Comment by navaj0** [comment] 2021-06-28 22:42
> I can confirm this happens regardless of the framework version and SDK version. It is a problem in the arguments passed to the `create_model()` request (ref: [L250](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/workflow/steps.py#L250)).

In the CreateModelStep, the model name is set to empty by design. When the pipeline runs, a unique model name is automatically assigned to the new model created.

**Closed** 2021-07-19 23:58 UTC
Labels: component: pipelines
