### ISSUE TITLE
`Estimator` environment variables are not passed to entry point script when using `HyperparameterTuner`

### ISSUE THREAD

**Issue by yuntan** [aws/sagemaker-python-sdk#2618] opened 2021-09-06 04:31 UTC
**Describe the bug**
Environment variables specified at `Estimator` class are not passed to the entry point script when running jobs by `HyperparameterTune` class.

**To reproduce**
[Dummy entry point script and notebook running sagemaker SDK](https://gist.github.com/yuntan/654a936c0cebb4e02505fae2f4a350ef)

**Expected behavior**
Training jobs run without failure and HyperParameterTuning job finishes without error. 

**Screenshots or logs**
Logs is shown in above link.

**System information**
- **SageMaker Python SDK version**: 2.59.1 (local)
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: TensorFlow
- **Framework version**: 2.4.1
- **Python version**: 3.9.4 (local)
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

related: #2311

**Comment by lorenzwalthert** [comment] 2022-05-22 20:33
This bug already costed me hours. -.- Any ETA of a fix @ahsan-z-khan or at least no slient failing?

**Comment by alar0330** [comment] 2022-07-10 09:07
@ahsan-z-khan, I also have this issue. Do we have any updates on this?

**Comment by lorenzwalthert** [comment] 2022-09-01 16:03
I think the problem is that the underlaying botocore functionality does [not exist](https://boto3.amazonaws.com/v1/documentation/api/1.9.185/reference/services/sagemaker.html#SageMaker.Client.create_hyper_parameter_tuning_job), not even sure it exists on the API level.

**Comment by DougTrajano** [comment] 2022-11-11 14:13
Hi folks, a workaround solution for that is to use the `hyperparameters` instead of `environment` in the Estimator API.

To don't change my estimator implementation, I added the code below in the hyperparameters code.

```python
for k, v in estimator.environment.items():
    estimator._hyperparameters[k] = v
```

In the `entry_point` script, I added all unexpected arguments as environment variables

```python
if len(remaining_args) > 0:
    for arg in range(len(remaining_args)):
        if remaining_args[arg].startswith("--"):
            os.environ[remaining_args[arg].strip("--")] = remaining_args[arg+1]
```

**Comment by lorenzwalthert** [comment] 2023-01-27 22:58
I think we can close this as per #3614.

**Comment by trungleduc** [comment] 2023-09-27 11:26
Closing as completed

**Closed by trungleduc** 2023-09-27 11:26 UTC
Labels: bug, component: training
