### ISSUE TITLE
Batch transform fails for large files

### ISSUE THREAD

**Issue by adiell** [aws/sagemaker-python-sdk#703] opened 2019-03-17 12:56 UTC
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow
- **Framework Version**: 1.12
- **Python Version**: py3
- **CPU or GPU**: CPU
- **Python SDK Version**:  1.18.3.post1
- **Are you using a custom image**: No

### Describe the problem
Batch transform works fine for small files, but fails for large files.

### Minimal repro / logs
I have a tensorflow model whose input are just two number.
When I use it to batch transform a file containing 10k rows, the job runs successfully.
When I run it on 100k rows, it fails. I tried multiple combinations of parameters (`max_payload`, `strategy`, `max_concurrent_transforms`, ...), but couldn't find a combination that works, or any example or tutorial that explains how to use these parameters.
- **Exact command to reproduce**:

```
from sagemaker.transformer import Transformer
transformer = Transformer(
    base_transform_job_name='Batch-Transform-demo',
    model_name='demo-2019-03-17-08-31-23-089',
    instance_count=1,
    instance_type='ml.c4.xlarge',
    output_path='s3://sagemaker-us-east-1-668139184987/batch_transform_demo/output/'
    )
s3_batch_transform_data = 's3://sagemaker-us-east-1-668139184987/batch_transform_demo/test_data_100k.csv'
transformer.transform(s3_batch_transform_data,                       
                      content_type='text/csv', split_type='Line')
```

Sample log:
```
12:30:43
[evhttp_server.cc : 237] RAW: Entering the event loop ...
12:31:09
169.254.255.130 - - [17/Mar/2019:12:31:09 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
12:31:09
169.254.255.130 - - [17/Mar/2019:12:31:09 +0000] "GET /execution-parameters HTTP/1.1" 404 22 "-" "Go-http-client/1.1"
12:31:11
2019/03/17 12:31:11 [notice] 11#11: signal 17 (SIGCHLD) received from 12
12:31:11
2019/03/17 12:31:11 [alert] 11#11: worker process 12 exited on signal 9
12:31:11
2019/03/17 12:31:11 [notice] 11#11: start worker process 66
12:31:11
2019/03/17 12:31:11 [notice] 11#11: signal 29 (SIGIO) received
12:31:12
2019/03/17 12:31:12 [notice] 11#11: signal 17 (SIGCHLD) received from 13
12:31:12
2019/03/17 12:31:12 [alert] 11#11: worker process 13 exited on signal 9
12:31:12
2019/03/17 12:31:12 [notice] 11#11: start worker process 67
12:31:12
2019/03/17 12:31:12 [notice] 11#11: signal 29 (SIGIO) received
12:32:12
2019/03/17 12:32:12 [info] 15#15: *6 client timed out (110: Connection timed out) while waiting for request, client: 169.254.255.130, server: 0.0.0.0:8080
12:32:12
169.254.255.130 - - [17/Mar/2019:12:32:12 +0000] "POST /invocations HTTP/1.1" 408 0 "-" "Go-http-client/1.1"
12:33:13
2019/03/17 12:33:13 [info] 66#66: *8 client timed out (110: Connection timed out) while waiting for request, client: 169.254.255.130, server: 0.0.0.0:8080
12:33:13
2019/03/17 12:33:13 [info] 67#67: *9 client timed out (110: Connection timed out) while waiting for request, client: 169.254.255.130, server: 0.0.0.0:8080
12:34:14
2019/03/17 12:34:14 [info] 67#67: *10 client timed out (110: Connection timed out) while waiting for request, client: 169.254.255.130, server: 0.0.0.0:8080
12:34:14
2019/03/17 12:34:14 [info] 67#67: *11 client timed out (110: Connection timed out) while waiting for request, client: 169.254.255.130, server: 0.0.0.0:8080
```

```
12:31:13
2019-03-17T12:31:09.670:[sagemaker logs]: MaxConcurrentTransforms=5, MaxPayloadInMB=2, BatchStrategy=MULTI_RECORD
12:34:14
2019-03-17T12:34:14.387:[sagemaker logs]: sagemaker-us-east-1-668139184987/batch_transform_demo/test_data_100k.csv: Unable to get response from algorithm
12:34:14
2019-03-17T12:34:14.496:[sagemaker logs]: sagemaker-us-east-1-668139184987/batch_transform_demo/test_data_100k.csv: Unable to get response from algorithm
```

**Comment by andremoeller** [comment] 2019-03-19 17:52
Hi @adiell ,

Could I ask you some questions first? These questions are just to help us understand usage a bit better:

1. Did you run a TensorFlow 'script mode' training job to create the model 'demo-2019-03-17-08-31-23-089'? If not, how did you create that model?
2. If so, did your 'script mode' script implement any serving functions, or did it only train and save the model?
3. How large is test_data_100k.csv (in MB or KB)?

Additionally, one suggestion to help in debugging is to add `strategy='SingleRecord'` to your Transformer's constructor. This will send one record at a time to the model.

Apologies on the poor documentation about these parameters -- this is a weak spot in our docs.

Thanks!

**Comment by adiell** [comment] 2019-03-20 09:37
Thanks @andremoeller ! Sure I'll be happy to provide any additional information to assist.
1. Yes, I ran a Tensorflow script mode training job on Sagemaker to create the model. I can provide the code if needed.
2. I just trained the model and saved it (using `SavedModelBuilder`). I did not implement serving functions. Can you point me to documentation or example on this? In any case, I managed to deploy the model to an endpoint, and running batch transform on smaller files.
3. It's 3.7MB

I tried running with `strategy='SingleRecord'`, but now I fail on different error:
```
{
    "error": "In[0] is not a matrix. Instead it has shape [2]\n\t [[{{node input_layer/MatMul}} = MatMul[T=DT_FLOAT, _output_shapes=[[?,10]], transpose_a=false, transpose_b=false, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_input_layer_input_0_0, input_layer/MatMul/ReadVariableOp)]]"
}
```

**Comment by andremoeller** [comment] 2019-03-23 04:33
Hi @adiell ,

It looks like at least one of your CSV inputs aren't in the format expected by your TensorFlow Serving model. We're working on ways to make what records are causing these failures more apparent.

That would explain why the SingleRecord request failed as it did, since it's sending one line of CSV at a time. But it looks from the logs you posted that the container timed out instead, and didn't respond with an error response at all (when it seems like it should have). I haven't gotten a chance to reproduce this, but I've opened an issue in the SageMaker Tensorflow Serving Container repository: https://github.com/aws/sagemaker-tensorflow-serving-container/issues/18

I mentioned serving functions earlier since SageMaker's other TensorFlow Serving image allows you to define your own Python functions to do pre- or post-processing or inference. For now, this TensorFlow Serving image doesn't support the same functionality, but that didn't come into play here (though it would be helpful for handling bad records). For now, I'd recommend ensuring that each row of CSV valid for the model -- it looks like in this case, a row didn't have as many columns as was expected.

**Comment by adiell** [comment] 2019-03-25 10:05
Thank you @andremoeller , I appreciate your help.
I', not sure I understand your response. The small and large csv are created in a similar way, and should not contain any "corrupted" row.
I uploaded the code that generates the model and performs the predictions (including the data generation) to [this gist](https://gist.github.com/adiell/0d20212a20ae3cabe38fadf25ebddd1b). 
It is self contained, and hopefully clear. 
If I ran it I get:
1. Estimator trained successfully.
2. Working predictor 
3. Successful batch transform on 100 rows
4. Failed batch transform on 100k rows.

**Comment by andremoeller** [comment] 2019-03-25 17:19
@adiell 

This is very helpful, thank you! We will work on reproducing this error and looking into why it fails. We'll keep this issue up to date.

**Comment by andremoeller** [comment] 2019-03-25 21:43
@adiell 

I reproduced both of your issues. For the timeouts with large payloads, I opened this issue in the SageMaker Tensorflow Serving repository: https://github.com/aws/sagemaker-tensorflow-serving-container/issues/18. I tried setting max_payload=1, the minimum, but unfortunately, the model server still timed out.

For the SingleRecord issue, I opened this issue in the SageMaker Tensorflow Serving repository: https://github.com/aws/sagemaker-tensorflow-serving-container/issues/20

I think we might not be handling single records of CSV (and possibly same for JSON) in the expected way. The container seems to be parsing "0.5,0.5" as two separate instances instead of one. We'll keep those issues up to date.

Thank you.

**Comment by adiell** [comment] 2019-03-26 06:19
Thanks @andremoeller !

**Comment by jesterhazy** [comment] 2019-04-04 00:12
closing, since the fix was released in https://github.com/aws/sagemaker-tensorflow-serving-container/releases/tag/v1.1.4

**Closed by jesterhazy** 2019-04-04 00:12 UTC

**Comment by adiell** [comment] 2019-04-08 09:38
Perfect, thanks!
