### ISSUE TITLE
Can't deploy Pytorch/flair model that I trained in JupyterLab

### ISSUE THREAD

**Issue by ShaneRyan1977** [aws/sagemaker-python-sdk#852] opened 2019-06-13 23:08 UTC
Please fill out the form below.

### System Information
- Framework : Pytorch
- Framework Version: 1.0.0
- Python Version: 3.5/3.6
- **CPU or GPU**: CPU
- **Python SDK Version**: Not sure
- Are you using a custom image: Yes

### Describe the problem
I trained a model in a Jupyter Lab using the "flair" library. Flair is an extension of PyTorch. It requires Python 3.6 to install.

I've been trying to deploy it to an endpoint. Using the code in: flair-deploy.py and model_methods.py the model itself is sitting in a file called flair-model.tar.gz in an s3 bucket. The flair-model.tar.gz contains one file called: model.pth

Over the course of trying to solve my issue. I've created two different Docker files.

The issue I am seeing is that the endpoint fails to deploy. The specific error from CloudWatch is:
> ImportError: No module named 'flair'

**Comment by ShaneRyan1977** [comment] 2019-06-13 23:09
> Here is the output from my Cloudwatch
> bash: cannot set terminal process group (-1): Inappropriate ioctl for device
> bash: no job control in this shell
> [2019-06-13 18:43:31 +0000] [21] [INFO] Starting gunicorn 19.9.0
> [2019-06-13 18:43:31 +0000] [21] [INFO] Listening at: unix:/tmp/gunicorn.sock (21)
> [2019-06-13 18:43:31 +0000] [21] [INFO] Using worker: gevent
> [2019-06-13 18:43:31 +0000] [28] [INFO] Booting worker with pid: 28
> [2019-06-13 18:43:31 +0000] [29] [INFO] Booting worker with pid: 29
> [2019-06-13 18:43:31 +0000] [33] [INFO] Booting worker with pid: 33
> [2019-06-13 18:43:31 +0000] [37] [INFO] Booting worker with pid: 37
> Processing /opt/ml/code
> Building wheels for collected packages: mnist Running setup.py bdist_wheel for mnist: started Running setup.py bdist_wheel for mnist: finished with status 'done' Stored in directory: /tmp/pip-ephem-wheel-cache-ufs3gl8c/wheels/35/24/16/37574d11bf9bde50616c67372a334f94fa8356bc7164af8ca3
> Successfully built mnist
> Installing collected packages: mnist
> Successfully installed mnist-1.0.0
> You are using pip version 18.1, however version 19.1.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> [2019-06-13 18:44:37 +0000] [28] [ERROR] Error handling request /ping
> Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_functions.py", line 84, in wrapper return fn(*args, **kwargs) File "/usr/local/lib/python3.5/dist-packages/mnist.py", line 159, in model_fn model.load_state_dict(torch.load(f)) File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 303, in load return _load(f,
> ImportError: No module named 'flair'

**Comment by ShaneRyan1977** [comment] 2019-06-13 23:11
[flair-deploy.py.txt](https://github.com/aws/sagemaker-python-sdk/files/3288390/flair-deploy.py.txt)

**Comment by ShaneRyan1977** [comment] 2019-06-13 23:12
[model_methods.py.txt](https://github.com/aws/sagemaker-python-sdk/files/3288392/model_methods.py.txt)

**Comment by ShaneRyan1977** [comment] 2019-06-13 23:13
[DockerFile.txt](https://github.com/aws/sagemaker-python-sdk/files/3288395/DockerFile.txt)

**Comment by ShaneRyan1977** [comment] 2019-06-13 23:17
What I don't understand is why the Sagemaker code is doing anything in the "/opt/ml/code" folder.
If I run the docker image in interactive mode there is nothing in that folder. For some reason why I try and deploy the endpoint the Sagemaker code dumps a bunch of stuff in there, and then installs Python 3.5 then complains that flair hasn't been installed.
I've double checked numerous time and "flair" is definitely installed. Just not for Python 3.5 which it doesn't support.

I hope and pray someone from AMZN can shine some light on what I am doing wrong. Many thanks in advance!

**Comment by mvsusp** [comment] 2019-06-14 19:24
Hi @ShaneRyan1977,

You don't need to create a new image to use the PyTorch container with additional dependencies. You can pass the requirements.txt file to the model as dependency:

```python
requirements = os.path.realpath("requirements.txt")

pytorch_model = PyTorchModel(model_data=S3_FILE_LOCATION, role= ROLE,  entry_point='model_methods.py', dependencies=[requirements], container_log_level="INFO")
```

These dependencies will be installed when the container starts. Notice that I am not using your image in the example. For information see: https://sagemaker.readthedocs.io/en/stable/using_pytorch.html#using-third-party-libraries

Thanks for using SageMaker!

**Comment by ShaneRyan1977** [comment] 2019-06-17 17:02
Hi @mvsusp 
Thanks for the suggestion! But that doesn't seem to make any difference. I am still seeing the exact same issues in CloudWatch. Eg. ImportError: No module named 'flair'

The logs don't say a lot but I can see after the workers are started that it processes the "/opt/ml/code" ( I didn't put anything in there). Then gets stuck in an infinite loop building mnist and trying to install "flair". Until the deployment image is killed as it doesn't ping.

I've spent a week fighting AWS Sagemaker. I think I'll try and deploy the model within a Lambda or maybe via Terraform. I don't see a huge benefit in deploying existing PyTorch models in Sagemaker over an AWS Lambda?

**Comment by mvsusp** [comment] 2019-06-17 20:22
@ShaneRyan1977 do you mind sharing the code that you used to trigger the training job allowing me to reproduce your issue?

**Comment by ShaneRyan1977** [comment] 2019-06-17 20:38
@mvsusp Very happy to!

```
from flair.data_fetcher import NLPTaskDataFetcher
from flair.embeddings import WordEmbeddings, FlairEmbeddings, DocumentLSTMEmbeddings, BertEmbeddings
from flair.models import TextClassifier
from flair.trainers import ModelTrainer
from pathlib import Path

corpus = NLPTaskDataFetcher.load_classification_corpus(Path('./'), test_file='test.csv', 
dev_file='dev.csv', train_file='train.csv')

word_embeddings = [BertEmbeddings('bert-base-uncased')]

document_embeddings = DocumentLSTMEmbeddings(word_embeddings, hidden_size=512, 
reproject_words=True, reproject_words_dimension=256)

classifier = TextClassifier(document_embeddings, 
label_dictionary=corpus.make_label_dictionary(), multi_label=False)

trainer = ModelTrainer(classifier, corpus)
trainer.train('./', max_epochs=10)
```
If my memory serves this creates a file called: best-model.pt which I renamed to "model.pth" tar'd and zipped to "flair-model.tar.gz" then uploaded to S3

**Comment by mvsusp** [comment] 2019-06-17 23:25
Sorry @ShaneRyan1977, I probably wasn't clear enough: The code that uses sageamerk to deploy the model after you changed it to included code dependencies. The original file name was `flair-deploy.py`

**Comment by ShaneRyan1977** [comment] 2019-06-18 17:16
No problem Marcio @mvsusp 

Just to be clear I have a model already trained with the script above. I am trying to deploy it to an endpoint.
Thanks

```
import sagemaker
from sagemaker import get_execution_role
import json
import boto3
import botocore
#import nltk
from sagemaker.pytorch.model import PyTorchModel
import os
import pdb
#pdb.set_trace()

#sess = sagemaker.Session()

ROLE = get_execution_role()
print(ROLE) # This is the role that SageMaker would use to leverage AWS resources (S3, CloudWatch) on your behalf

BUCKET = "sagemaker-shane-ohio" 
PREFIX = 'flair' #Replace with the PREFIX under which you want to store the data if needed
KEY = 'flair-model.tar.gz'

S3_FILE_LOCATION = 's3://{}/{}/{}'.format( BUCKET, PREFIX, KEY)
#check_model_on_s3(BUCKET, KEY)

print(S3_FILE_LOCATION)

cwd = os.path.dirname(os.path.realpath("requirements.txt"))
print("Current working Directory: " + cwd)

ENDPOINT_NAME = "flair-model"
#file_url = "https://sagemaker-shane-ohio.s3.us-east-2.amazonaws.com/flair/model.tar.gz"

requirements = os.path.realpath("requirements.txt")
pytorch_model = PyTorchModel(model_data=S3_FILE_LOCATION, role= ROLE,  entry_point='model_methods.py', dependencies=[requirements], container_log_level="INFO")

#pytorch_model = PyTorchModel(model_data=S3_FILE_LOCATION, role= ROLE,  entry_point='model_methods.py', source_dir=cwd, py_version='py3', framework_version='1.0.0', name=ENDPOINT_NAME)
pytorch_model = PyTorchModel(model_data=S3_FILE_LOCATION, role= ROLE,  entry_point='model_methods.py', image='984153553444.dkr.ecr.us-east-2.amazonaws.com/black-tusk2:latest', container_log_level="INFO")
#pytorch_model = PyTorchModel(model_data=S3_FILE_LOCATION, role= ROLE,  entry_point='model_methods.py', source_dir=cwd, image='984153553444.dkr.ecr.us-east-2.amazonaws.com/black-tusk:latest')
#pytorch_model = PyTorchModel(model_data=S3_FILE_LOCATION, role= ROLE,  entry_point='model_methods.py', image='984153553444.dkr.ecr.us-east-2.amazonaws.com/black-tusk:latest',py_version='py36', framework_version='1.0.0', name=ENDPOINT_NAME)
#pytorch_model = PyTorchModel(model_data=S3_FILE_LOCATION, role=ROLE, entry_point='model_methods.py', sagemaker_session=sess, py_version='py3', framework_version='1.0.0', name=ENDPOINT_NAME)



predictor = pytorch_model.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge', endpoint_name=ENDPOINT_NAME)
#predictor = pytorch_model.deploy(1, 'ml.m4.xlarge', endpoint_name=ENDPOINT_NAME)
```

**Comment by jesterhazy** [comment] 2019-06-19 20:27
@ShaneRyan1977 

It looks like you are assigning to `pytorch_model` twice (and creating two different model entities). The  second assignment does not include the `dependencies=[requirements]` parameter, and that's the one that is being used to deploy the endpoint.

**Comment by ShaneRyan1977** [comment] 2019-06-19 21:56
@jesterhazy Good catch. But that was just a mis-type on my part. I've tried every possible combination of parameters for the PyTorchModel known to man.

After commenting out the second assignment I am still seeing the exact same issues in CloudWatch. Eg. ImportError: No module named 'flair'

Like I mentioned earlier. 'flair' requires python 3.6 but there error seems to originate from python 3.5 code being run.
```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_functions.py", line 84, in wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/mnist.py", line 159, in model_fn
model.load_state_dict(torch.load(f))
File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 303, in load
return _load(f, map_location, pickle_module)
File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 469, in _load
result = unpickler.load()
```
Is there anything I can do to force sagemaker to run it's code in python 3.6 instead of python 3.5?
The Jupyter Lab that I did the training in is 3.6 compatible.
I've created my own custom docker image with only python 3.6
But somehow like a virus sagemaker keeps installing python 3.5

**Comment by icywang86rui** [comment] 2019-07-01 15:39
@ShaneRyan1977 
Our container only has python 3.5 installed. To use python 3.6 you will have to install it in your training script from source, probably at the top, and install any python 3.6 dependencies afterwards.

**Comment by laurenyu** [comment] 2019-09-06 20:27
closing due to inactivity. Also, I believe the PyTorch 1.1.0 images now use Python 3.6.

**Closed by laurenyu** 2019-09-06 20:27 UTC
