### ISSUE TITLE
Using customized tensor name for prediction after deploying the model

### ISSUE THREAD

**Issue by vbvg2008** [aws/sagemaker-python-sdk#394] opened 2018-09-19 03:18 UTC
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: TensorFlow
- **Framework Version**: 1.10
- **Python Version**: 2.7
- **CPU or GPU**: GPU 
- **Are you using a custom image**: No

### Describe the problem
All of the Sagemaker tensorflow tutorial uses "inputs" as the input name for prediction.  for example, in "tensorflow_resnet_cifar10_with_tensorboard" example, the prediction is simply done by 

random_image = np.random.rand(32, 32, 3)
predictor.predict(random_image_data)

but what if I trained a tensorflow model with a customized input name?  say my model inputs only accepts a dictionary like this: 
inputs = {"input_image": tf.placeholder(tf.float32, [None, 32, 32, 3])}

Although I successfully trained and deployed the model, but when I try to do the prediction such as:

random_image = np.random.rand(32, 32, 3)
predictor.predict({'input_image':random_image})

it gives me error saying my data is not JSON serializable. How do I use a customized name as input name for prediction?

**Comment by mvsusp** [comment] 2018-09-20 00:31
Hello @vbvg2008 ,

I believe that this issue is related to https://github.com/aws/sagemaker-tensorflow-container/issues/71.
We are in the process to release a newer container with these codefixes. I will update you in this ticket when it happens.

Thanks for using SageMaker!

**Comment by winstonaws** [comment] 2018-09-25 22:20
@mvsusp The problem is fixed on the container side, but now we need to make a fix to the Python SDK to serialize numpy arrays in dicts correctly.

@vbvg2008 in the meantime, if you want to unblock yourself, try the workaround described here:
https://github.com/aws/sagemaker-tensorflow-container/issues/71#issuecomment-422101489

Basically, convert your numpy arrays into lists before putting them in the dict.

**Comment by eL0ck** [comment] 2018-10-05 04:03
hi @winstonaws,  
I am running into an issue that seems like it may be related.  I have logged it under issue #413.
If you have any idea on how to coerce my input data into an acceptable format I would very much appreciate it.

**Comment by icywang86rui** [comment] 2018-10-10 17:08
hi @eL0ck,

We have merged in a change to accept dicts with numpy arrays on the python sdk side - #404 .
Your original way to do the prediction should work now: 

random_image = np.random.rand(32, 32, 3)
predictor.predict({'input_image':random_image})

Please let us know if the problems persists.

**Closed** 2018-12-20 21:09 UTC
Labels: bug, duplicate
