### ISSUE TITLE
Hyper Parameter Validation

### ISSUE THREAD

**Issue by ChandraLingam** [aws/sagemaker-python-sdk#132] opened 2018-04-06 16:48 UTC
If I pass in an incorrect value for a hyper parameter or if a required hyper parameter is missing, Estimator fit method takes 5-6 minutes to fail and report back the issue.

It will be nice if there is a check either at sdk level or SageMaker service level to catch these configuration issues and report back right away.

**Comment by yangaws** [comment] 2018-04-06 18:45
Hi,

Thanks for using sagemaker!

Could you give an example of the hyper-parameter validation? We actually have basic validations in our sdk. 

Thanks

**Comment by yangaws** [comment] 2018-04-06 22:04
More things to add. 

We have most hyper-parameter validations(some exceptions) in our amazon first party algorithms. If you found one with incorrect validations, you are more than welcome to report to us. 

But if you are using our framework, then could you please tell us what framework you are using and what hyper-parameter you want validation on?

Thanks

**Comment by ChandraLingam** [comment] 2018-04-06 23:37
To give two examples: 
XGBoost - If you don't specify **num_round** and try to fit the data, fit method responds back after 6 minutes that required parameter is missing.
PCA - if you don't specify **mini_batch_size**, you get an error like this (after 6 minutes):
Failure reason
ClientError: No value(s) were specified for 'mini_batch_size' which are required hyperparameter(s) (caused by ValidationError) Caused by: u'mini_batch_size' is a required property Failed validating u'required' in schema: {u'$schema': u'http://json-schema.org/schema#', u'additionalProperties': False, u'properties': {u'_kvstore': {u'enum': [u'auto', u'local', u'device', u'dist_sync', u'dist_async'], u'type': u'string'}, u'_log_level': {u'enum': [u'debug', u'info', u'warning', u'error', u'critical'], u'type': u'string'},

**Comment by yangaws** [comment] 2018-04-07 00:27
Cool. I get your problem. 

XGBoost is a special algorithm we support. Unlike other algorithms that have their own estimator which handles most hyper-parameter validation, XGBoost uses the general sagemaker estimator that doesn't validate.

The problem is, since it's a general estimator, it's not only used for xgboost. So I am not 100% confident that we have a simple way for validation in xgboost. But what you raised here is definitely a good point. XGBoost has so many hyper-parameters to tune. We should have more validation to save users' time.

I will discuss with other developers and get back to you later.

This will be marked as a feature request.

Thanks for your suggestion!

**Comment by ChandraLingam** [comment] 2018-04-10 20:01
Thank you @yangaws  for taking a look at this!  
If I may add my 2 cents, it will be nice if the AWS SageMaker service itself does some checks like these and respond right back if the request is not valid (instead of erroring out after 5 minutes)

**Comment by trungleduc** [comment] 2023-12-21 14:56
Closing since the required feature needs to be implemented at the SageMaker service level, and not at the SDK level. Please feel free to re-open for more discussion.

**Closed by trungleduc** 2023-12-21 14:56 UTC
Labels: type: feature request, component: training
