### ISSUE TITLE
pipeline uses CreateModelStep name for model name, not model name

### ISSUE THREAD

**Issue by neilmcguigan** [aws/sagemaker-python-sdk#2650] opened 2021-09-22 05:57 UTC
```
model = Model(
    image_uri=image_uri,
    model_data=training_step.properties.ModelArtifacts.S3ModelArtifacts,
    role=role,
    sagemaker_session = sagemaker_session,
    name="model2" # this doesn't seem to be used
)

model_input = CreateModelInput(
    instance_type="ml.m5.large"
)

create_model_step = CreateModelStep(
    name="mymodel", # this is used as the model name
    model = model,
    inputs=model_input
)
```

**Comment by peter-resnick** [comment] 2021-09-27 22:46
I have also noticed this behavior - makes it very difficult to manage model naming in an automated fashion using any standard naming conventions that a team may have. 

This should probably be logged as a bug

**Comment by ahsan-z-khan** [comment] 2021-09-30 20:43
Hi @neilmcguigan ,

Thanks for using Amazon SageMaker. 

Can you update the issue with how to reproduce it? and your system information?

**Comment by peter-resnick** [comment] 2021-09-30 21:55
I can provide my info (I'm experiencing the same):

**Describe the bug**
When executing a SageMaker Pipeline the includes a `CreateModelStep` step, the model name is not propagated from the `Model` object which is passed to it. Instead, the Step creates its own name for the model based on the pipeline step/name. 

This is occuring in SageMaker Studio Notebooks.

**To reproduce**

```
import sagemaker
import boto3

from sagemaker.model import Model
from sagemaker.inputs import CreateModelInput
from sagemaker.workflow.steps import CreateModelStep

from sagemaker.workflow.pipeline import Pipeline

session = sagemaker.session.Session()
region = boto3.Session().region_name
image_uri = sagemaker.image_uris.retrieve(region=region, framework="xgboost", version="0.90-2") 

cable_model = Model(
    image_uri=image_uri,
    model_data=<path_to_model_in_s3>,
    sagemaker_session=session,
    role=role,
    name=<the_name_the_model_should_have>,
)

cable_model_inputs = CreateModelInput(
    instance_type="ml.m5.large",
)

step_create_model = CreateModelStep(
    name="step-create-model",
    model=cable_model,
    inputs=cable_model_inputs,
)

create_model_pipeline = Pipeline(name="create_model_pipeline", steps=[step_create_model])
create_model_pipeline.create(role_arn=role)
create_model_pipeline.start(execution_display_name="create_my_model_pipeline")
```

**Expected behavior**

We would expect that when the pipeline runs, the create model step should create a model with <the_name_the_model_should_have> as the name that is populated in the SageMaker UI and the API returns

**Screenshots or logs**

![image](https://user-images.githubusercontent.com/32655722/135535187-f5121799-0705-48a3-970e-a115f29b1309.png)
This is the model that is created by the step, its a "pipelines-..." prefix that then includes the name of the pipeline step and some additional alphanumerics dropped in (which would suggest that SageMaker Pipelines thinks there has been no model name passed to the pipeline and it needs to create a unique name automatically - which it should not be doing since the `Model` object we pass the step already has a `name` defined. 

SageMaker Python SDK version: 2.52.2
Framework name (eg. PyTorch) or algorithm (eg. KMeans): N/a
Framework version: N/A
Python version: 3.7.10
CPU or GPU: CPU
Custom Docker image (Y/N): N

**Comment by snowolf** [comment] 2021-12-09 10:43
Just found "step_create_model.properties.ModelName" may work.

**Comment by akashsingla** [comment] 2021-12-09 16:01
> Just found "step_create_model.properties.ModelName" may work.

It works to only provide you a random name which uses CreateModelStep name.

The workaround specified above seems interesting.

In our scenario,
We create a new model name by using timestamp for every execution and wish to use that when CreateModelStep runs. However, looks like it is ignored.

I'll try the workaround for now but would appreciate if the sagemaker team could allow the use of the **name** arg of Model class the way it is expected and maybe add some documentation around it to explain users what would happen if static model names are used.
I feel it should be the responsibility of the team building the model pipeline to govern names, not enforced by sagemaker.

**Comment by danielsiwiec** [comment] 2022-01-31 21:40
I'm also hoping for a resolution to this issue

**Comment by andre-marcos-perez** [comment] 2022-10-22 02:47
How about SageMaker only prefixing the step name with a unique key?

**Comment by clausagerskov** [comment] 2022-11-07 11:36
@staubhp anything?

**Comment by HarryPommier** [comment] 2022-11-29 16:30
I also think that the current model naming strategy with create_model does not allow for robust model management. For example, if we want to retrieve with a stepfunction (ListModels, createTransformJob) a model created during the execution of a pipeline. In this case, we need a static element in the name of the model to be able to associate it to the right project.

**Comment by Rainfarm** [comment] 2023-11-08 16:43
I think specifying model name in a pipeline is needed in some scenarios. For example, I want to create a model from model group in a ModelStep (named "createModel") and use that to run a ClarifyCheckStep. For a ClarifyCheckStep, a ModelConfig needs to be provided, but the model name created cannot be used in setting ModelConfig (see the 2nd line below):
```python
model_config = ModelConfig(
      model_name=createModel.properties.ModelName,  # this does NOT work.
      instance_type=inferencing_instance_type,
      instance_count=1,
      accept_type="text/csv",
  )
```
If the `ModelConfig.model_name` can be set with the value of `<create-model-step>.properties.ModelName`, then I agree there's no need to specify a name explicitly.
So, in general, I don't think this is a request of new feature, at least not 100%.

**Comment by ShwetaSingh801** [comment] 2023-12-22 04:41
Hi @neilmcguigan,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request to our backlog and may consider putting it into future SDK versions. I will go ahead and close the issue now. Please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta

**Closed** 2023-12-22 04:41 UTC
Labels: type: feature request, component: pipelines
