### ISSUE TITLE
Unable to use custom inference code when deploying XGBoost model from a model package registered via SM pipeline execution

### ISSUE THREAD

**Issue by giuseppeporcelli** [aws/sagemaker-python-sdk#2014] opened 2020-12-04 21:41 UTC
**Describe the bug**
I have created a two-step SM pipeline that trains a XGBoost model using the XGB framework and then registers the model in the model registry, also providing a custom inference script.
When the model is created from the model package in the registry and then deployed to a SM endpoint, the endpoint is successfully created, but the custom inference code is not loaded/invoked.

**To reproduce**
1. Create a SM Estimator for training a XGB model using SageMaker's XGBoost framework and a custom training script
2. Create a SM Pipeline's TrainingStep using the estimator as input
3. Create a SM Pipeline's RegisterModel step passing the additional parameters entry_point and source_dir to specify a custom inference script
4. Create the pipeline using the steps above and execute it.
5. Create a ModelPackage object, setting the model_package_arn parameter to the arn of the model package version created by the pipeline execution
6. Call the deploy() method of the ModelPackage object to deploy the model
7. Execute some inferences and realize that the custom inference script is not invoked

**Expected behavior**
Looking at the code, the RegisterModel step takes care of re-packing the model.tar.gz to include the code in the source_dir and any dependencies in the archive itself. Some points I would consider (IMHO) are:
1. AFAIK, the XGBoost container is not able to load a custom inference script from the model.tar.gz when MMS is not the serving stack (the container defaults to nginx-gunicorn-flask when operating with single-model). This applies also to other containers (e.g. SKLearn).
2. Even when using MMS, the custom inference script should be under /code and not at the same level of the serialized model in the root of the archive. When uncompressing the re-packed archive, I found the code at the root.
3. If the custom inference script is named "xxx.py" I haven't seen any way to specify what is the Python module that has to be loaded (there used to be an environment variable to set it).

If I can provide a suggestion, it would be nice allowing to specify a collection of environment variables for a model package, as this is the way serving containers used to access inference code archive paths. Additionally, this capability would allow to associate default environment variables for a model in the registry, to control certain settings like number of workers, etc.
When a model is created from a model package, the collection could be copied to the model, unless overridden.

Alternatively, it would be great to have feature parity on how framework containers load custom code for inference (e.g. enforce that custom code has to be always under /code in the model.tar.gz archive for all supported serving stacks). 

**Screenshots or logs**
N/A

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.18.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: XGBoost
- **Framework version**: 0.90-2
- **Python version**: 3.x
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**

**Comment by ajaykarpur** [comment] 2020-12-07 19:50
Hi @giuseppeporcelli, thanks for bringing this to our attention! @balajitummala, can you investigate the issue with the XGBoost container serving stack?

**Comment by cfregly** [comment] 2020-12-22 05:03
@ajaykarpur @giuseppeporcelli this is more than just the XGBoost container.  This is happening with my and @antje's TensorFlow + BERT pipeline, as well, using the TensorFlow 2.1 deep learning container.

The issue is that we can't specify a src/ (or code/) directory that contains our `inference.py`.  This seems like a larger issue.

Can you help unblock us?  Is there a workaround?  We can't deploy our models properly.

Here is the SM Pipeline that we're trying to deploy:  https://github.com/data-science-on-aws/workshop/tree/b8b6533/11_pipeline/project-dsoaws-p-ibxfjw9nuim7/sagemaker-project-dsoaws-p-ibxfjw9nuim7-modelbuild/pipelines/dsoaws

**Comment by giuseppeporcelli** [comment] 2020-12-29 17:12
@cfregly You can define the `entry_point` and `source_dir` parameters via the `RegisterModel` step as shown here https://github.com/aws/sagemaker-python-sdk/blob/83afa36b6b61926d0a29b14006de222e4a028792/src/sagemaker/workflow/step_collections.py#L95

However, I'm not sure the content of the `source_dir` is correctly placed under `/code` as I explained above.

**Comment by kirit93** [comment] 2021-05-27 14:32
@giuseppeporcelli - there was a recent bug fix in the sdk and you'll find the the contents of `source_dir` are now placed under `code/` in `model.tar.gz`.

**Comment by jerrypeng7773** [comment] 2022-02-14 22:13
https://github.com/aws/sagemaker-python-sdk/pull/2755 this PR is merged, if you encounter further issue, feel free to re-open.

**Closed by jerrypeng7773** 2022-02-14 22:13 UTC
Labels: XGBoost, component: pipelines
